server:
  port: 8002
spring:
  application:
    name: user-auth-service
  datasource:
    # 配置mysql数据库
    url: jdbc:mysql://localhost:3306/personnel_management
    username: root
    password: xm
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  redis:
    #Redis服务器地址
    host: 127.0.0.1
    #端口
    port: 6379
    #使用几号数据库
    database: 0
  # 配置邮件发送
  mail:
    # 163邮箱的地址为smtp.163.com，直接填写即可
    host: smtp.163.com
    # 你申请的163邮箱
    username: 18307478153@163.com
    # 注意密码是在开启smtp/pop3时自动生成的，记得保存一下，不然就找不到了
    password: CHXQPBKVRIGKTFMB
  cloud:
    nacos:
      discovery:
        # 配置nacos注册中心地址
        server-addr: localhost:8848
# 阿里爸爸能不能别log了
logging:
  level:
    com.alibaba.nacos.client.naming: WARN
    com.alibaba.nacos.client.config.impl: WARN
