spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personnel_management
    username: root
    password: xm
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  jpa:
    #开启SQL语句执行日志信息
    show-sql: true
    hibernate:
      #配置为自动创建
      ddl-auto: update