
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personnel_management
    username: root
    password: xm
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  redis:
    #Redis服务器地址
    host: 127.0.0.1
    #端口
    port: 6379
    #使用几号数据库
    database: 0
server:
  port: 8002