spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personnel_management
    username: root
    password: xm
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:db/migration # 默认配置
    enabled: true # 默认
    baseline-on-migrate: true
    clean-on-validation-error: false