spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personnel_management
    username: root
    password: xm
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #开启SQL语句执行日志信息
    show-sql: true
    # 也可以设置jpa.generate-ddl:false
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration # 默认配置
    enabled: true # 默认
    baseline-on-migrate: true
    clean-on-validation-error: false
server:
  port: 8001